# This file was generated by GoReleaser. DO NOT EDIT.
cask "markdown-reviewer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/markdown-review-server"]
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/mr"]
    end
  end

  version "0.34.0"

  on_macos do
    on_arm do
      sha256 "5d8766c58d70b712b7af2b1df69f75a89e4a0a49807e58fdbd419393018f9ecc"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2329108f1a92115c0d4af61fbd4a7adf15337dc80f8dd7e2cb602d1e6eabc13e"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c24b3f4d8de2390cef6b04ce5c6cc33b31c0727c5c57bbcfc6389f3c202da1c7"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee872ef0fbfc0bb7e5b34ba61d7f2eb698a0749abdfb0b458b15663088807383"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "markdown-reviewer"
  desc "Review local Markdown in a web editor with sidecar comments, AI-friendly via the bundled mr CLI"
  homepage "https://github.com/rengotaku/markdown-reviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markdown-review-server"
  binary "mr"

  # No zap stanza required

  caveats <<~EOS
    起動例:
      REVIEW_ROOT=$HOME/notes markdown-review-server
    コメントの読み書き (AI 向け CLI):
      mr inbox / mr review <path> / mr reply / mr resolve
  EOS
end
