# This file was generated by GoReleaser. DO NOT EDIT.
cask "markdown-reviewer" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "66f151883ef06ae9c646c9a2222760586ff75f77c224f346fae356304f121c49"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a356d12c59139ee6bf2a65d8bab47e8c97fb5b159b4b49ad34d79e149684dbf0"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aadec93ce5fbdf1318c1c67cffa5749f7533a733e6949f5f5323439ca0b4a7c6"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8c9e5ac692715b65ea5eb0ef0d14187abc63e73a3811cbd0b67a9338ce5e651"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "markdown-reviewer"
  desc "Review local Markdown in a web editor with sidecar comments, AI-friendly via the bundled mr CLI"
  homepage "https://github.com/rengotaku/markdown-reviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markdown-review-server"
  binary "mr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/markdown-review-server"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mr"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    起動例:
      REVIEW_ROOT=$HOME/notes markdown-review-server
    コメントの読み書き (AI 向け CLI):
      mr inbox / mr review <path> / mr reply / mr resolve
  EOS
end
