# This file was generated by GoReleaser. DO NOT EDIT.
cask "markdown-reviewer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/markdown-review-server"]
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/mr"]
    end
  end

  version "0.35.0"

  on_macos do
    on_arm do
      sha256 "d2f8231d72393db98d3ba64054d95b17a7f27b86061025410cd62a10d6bc08ba"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1627fafaa138e680638824c05c1a4a483c53f364273d1288e5571e1f494f1f7"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cb524c722e8389311799b0cc5b97c585f9bc9b2a45dba6d8b9880708a05dc1f7"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d5d73911442959b9a4694222374583ad152ebd4b4f74fe2381a068886f918b8"
      url "https://github.com/rengotaku/markdown-reviewer/releases/download/v#{version}/markdown-reviewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "markdown-reviewer"
  desc "Review local Markdown in a web editor with sidecar comments, AI-friendly via the bundled mr CLI"
  homepage "https://github.com/rengotaku/markdown-reviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markdown-review-server"
  binary "mr"

  # No zap stanza required

  caveats <<~EOS
    起動例:
      REVIEW_ROOT=$HOME/notes markdown-review-server
    コメントの読み書き (AI 向け CLI):
      mr inbox / mr review <path> / mr reply / mr resolve
  EOS
end
